"""Browser UI for the Intelligence Case Intake vertical slice.

The page is deliberately a thin client: Supabase Auth handles the session and
all case operations go through the authenticated server API. No service-role
credential or provider key is rendered to the browser.
"""
from __future__ import annotations

import html
import os

from fastapi.responses import HTMLResponse


def cases_page() -> HTMLResponse:
    supabase_url = html.escape(os.getenv("SUPABASE_URL", ""), quote=True)
    publishable_key = html.escape(os.getenv("SUPABASE_PUBLISHABLE_KEY", ""), quote=True)
    return HTMLResponse(f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0f172a"><title>Intelligence Cases — AI Platform</title>
<style>
:root{{--nav:#0f172a;--nav2:#111c31;--bg:#f4f6f8;--panel:#fff;--line:#e2e8f0;--text:#172033;--muted:#64748b;--blue:#2563eb;--green:#059669;--amber:#d97706;--violet:#7c3aed;--gray:#64748b;--danger:#dc2626}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}button,input,textarea,select{{font:inherit}}button{{cursor:pointer}}
.shell{{min-height:100svh;display:grid;grid-template-columns:248px 1fr}}.side{{background:var(--nav);color:#cbd5e1;padding:20px 14px;display:flex;flex-direction:column;gap:24px}}.brand{{display:flex;align-items:center;gap:10px;color:#fff;font-weight:750;font-size:16px;padding:4px 8px}}.mark{{width:32px;height:32px;border-radius:9px;background:#1d4ed8;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:800}}.nav{{display:grid;gap:5px}}.nav a{{color:#94a3b8;text-decoration:none;padding:10px 11px;border-radius:8px}}.nav a.active,.nav a:hover{{background:#1e293b;color:#fff}}.sideFoot{{margin-top:auto;font-size:12px;color:#64748b;padding:8px}}
.main{{min-width:0}}.top{{height:64px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;position:sticky;top:0;z-index:5}}.crumb{{font-weight:700}}.user{{display:flex;align-items:center;gap:10px;color:var(--muted);font-size:12px}}.logout,.secondary{{border:1px solid var(--line);background:#fff;border-radius:8px;padding:8px 11px;color:var(--text)}}
.content{{padding:28px;max-width:1500px;margin:auto}}.headline{{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:22px}}h1{{margin:0;font-size:27px;letter-spacing:-.03em}}.sub{{margin:5px 0 0;color:var(--muted)}}.primary{{border:0;border-radius:8px;padding:10px 14px;background:var(--blue);color:#fff;font-weight:700}}.primary:disabled{{opacity:.55;cursor:wait}}
.metrics{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}}.metric{{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px}}.metric b{{display:block;font-size:22px;margin-top:7px}}.metric span{{font-size:12px;color:var(--muted)}}
.toolbar{{background:#fff;border:1px solid var(--line);border-radius:10px;padding:12px;display:flex;gap:9px;margin-bottom:12px}}.toolbar input,.toolbar select,.field input,.field textarea,.field select{{border:1px solid var(--line);border-radius:8px;padding:10px;background:#fff;color:var(--text);outline:none}}.toolbar input{{flex:1;min-width:180px}}.toolbar select{{min-width:145px}}
.table{{background:#fff;border:1px solid var(--line);border-radius:10px;overflow:hidden}}table{{width:100%;border-collapse:collapse}}th,td{{padding:13px 15px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}}th{{font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);background:#f8fafc}}tbody tr{{cursor:pointer}}tbody tr:hover{{background:#f8fafc}}td small{{display:block;color:var(--muted);margin-top:4px}}
.badge{{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:750}}.open{{background:#eff6ff;color:#1d4ed8}}.in_progress{{background:#fef3c7;color:#92400e}}.resolved{{background:#ecfdf5;color:#047857}}.closed{{background:#f1f5f9;color:#475569}}.claim{{background:#fffbeb;color:var(--amber)}}.inference{{background:#f5f3ff;color:var(--violet)}}.unknown{{background:#f1f5f9;color:var(--gray)}}.fact{{background:#ecfdf5;color:var(--green)}}
.detail{{display:none;grid-template-columns:minmax(0,1fr) 390px;gap:14px}}.back{{margin-bottom:14px;color:var(--blue);background:none;border:0;padding:0;font-weight:650}}.card{{background:#fff;border:1px solid var(--line);border-radius:10px;padding:18px;margin-bottom:14px}}.cardHead{{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}}.card h2{{font-size:15px;margin:0}}.caseTitle{{font-size:22px;font-weight:750;letter-spacing:-.02em;margin:0 0 5px}}.summary{{line-height:1.6;color:#334155;white-space:pre-wrap}}.metaGrid{{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}}.metaGrid div{{background:#f8fafc;border-radius:8px;padding:10px}}.metaGrid span{{display:block;font-size:10px;text-transform:uppercase;color:var(--muted);letter-spacing:.06em;margin-bottom:4px}}
.assertion{{border:1px solid var(--line);border-radius:9px;padding:13px;margin-top:9px}}.assertionTop{{display:flex;justify-content:space-between;gap:10px}}.assertion p{{margin:8px 0 0;line-height:1.5}}.assertion small{{color:var(--muted)}}.governance{{margin-top:9px;background:#f8fafc;border-radius:8px;padding:9px;font-size:11px;color:var(--muted)}}.question{{border-top:1px solid var(--line);padding:11px 0;line-height:1.45}}.question:first-child{{border-top:0}}
.evidence{{border:1px solid var(--line);border-radius:8px;padding:11px;margin-top:8px}}.evidence b{{font-size:12px}}.evidence p{{margin:7px 0;line-height:1.45;white-space:pre-wrap}}.source{{font-size:11px;color:var(--muted);word-break:break-all}}.audit{{border-left:2px solid #cbd5e1;padding:0 0 13px 13px;margin:0 0 0 5px}}.audit:last-child{{padding-bottom:0}}.audit b{{font-size:12px}}.audit small{{display:block;color:var(--muted);margin-top:3px}}.digest{{font:10px ui-monospace,SFMono-Regular,Menlo,monospace;color:#64748b;word-break:break-all;margin-top:4px}}
.modal{{position:fixed;inset:0;background:rgba(15,23,42,.55);display:none;align-items:center;justify-content:center;padding:18px;z-index:20}}.modalBox{{width:min(620px,100%);background:#fff;border-radius:12px;padding:20px;box-shadow:0 20px 60px rgba(15,23,42,.25)}}.modalHead{{display:flex;justify-content:space-between;align-items:center}}.modalHead h2{{margin:0;font-size:17px}}.close{{border:0;background:none;font-size:22px;color:var(--muted)}}.field{{display:grid;gap:6px;margin-top:13px}}.field label{{font-size:12px;font-weight:700}}.field textarea{{min-height:120px;resize:vertical}}.modalActions{{display:flex;justify-content:flex-end;gap:8px;margin-top:17px}}.notice{{padding:10px 12px;border-radius:8px;margin:0 0 12px;font-size:12px;background:#eff6ff;color:#1e40af}}.error{{background:#fef2f2;color:#991b1b}}
.auth{{min-height:100svh;display:grid;place-items:center;padding:20px}}.authBox{{width:min(420px,100%);background:#fff;border:1px solid var(--line);border-radius:12px;padding:24px}}.authBox h1{{font-size:22px}}.authBox p{{color:var(--muted);line-height:1.5}}.authBox .field input{{width:100%}}.authBox .primary{{width:100%;margin-top:16px}}.switch{{border:0;background:none;color:var(--blue);margin-top:12px;width:100%}}
@media(max-width:900px){{.shell{{grid-template-columns:1fr}}.side{{display:none}}.content{{padding:18px 12px}}.metrics{{grid-template-columns:1fr 1fr}}.detail{{grid-template-columns:1fr}}.top{{padding:0 14px}}.user span{{display:none}}}}@media(max-width:600px){{.metrics{{grid-template-columns:1fr 1fr}}.toolbar{{flex-wrap:wrap}}.toolbar input{{min-width:100%}}table,thead,tbody,th,td,tr{{display:block}}thead{{display:none}}tbody tr{{padding:10px 12px;border-bottom:1px solid var(--line)}}td{{border:0;padding:5px 2px}}td:before{{content:attr(data-label);font-size:10px;text-transform:uppercase;color:var(--muted);display:block;margin-bottom:2px}}}}
</style></head><body>
<div id="authView" class="auth"><div class="authBox"><div class="brand" style="padding:0;color:var(--text)"><div class="mark">AI</div><span>AI Platform</span></div><h1 style="margin-top:24px">Intelligence Cases</h1><p>Sign in to access governed case intake, AI-assisted triage, evidence provenance and the immutable audit trail.</p><form id="authForm"><div class="field"><label>Email</label><input id="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password" minlength="6" required></div><button id="authSubmit" class="primary">Sign in</button></form><button id="switch" class="switch">Create an account</button><div id="authNotice" class="notice error" hidden></div></div></div>
<div id="appView" class="shell" hidden><aside class="side"><div class="brand"><div class="mark">AI</div><span>AI Platform</span></div><nav class="nav"><a class="active" href="#">Intelligence Cases</a><a href="/app">Model Chat</a></nav><div class="sideFoot">Governed execution · tenant isolated</div></aside><section class="main"><header class="top"><div class="crumb">Case Operations</div><div class="user"><span id="userEmail"></span><button id="logout" class="logout">Log out</button></div></header><main class="content"><div id="listView"><div class="headline"><div><h1>Intelligence Cases</h1><p class="sub">Review reported problems, triage assertions and verify evidence.</p></div><button id="newCase" class="primary">+ New case</button></div><div id="globalNotice" class="notice" hidden></div><div class="metrics"><div class="metric"><span>Total cases</span><b id="mTotal">—</b></div><div class="metric"><span>Open</span><b id="mOpen">—</b></div><div class="metric"><span>In progress</span><b id="mProgress">—</b></div><div class="metric"><span>Resolved / closed</span><b id="mDone">—</b></div></div><div class="toolbar"><input id="search" placeholder="Search cases…"><select id="status"><option value="">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><button id="refresh" class="secondary">Refresh</button></div><div class="table"><table><thead><tr><th>Case</th><th>Status</th><th>Created</th><th>Updated</th></tr></thead><tbody id="caseRows"></tbody></table></div></div>
<div id="detailView" class="detail"><div><button id="back" class="back">← Back to cases</button><div class="card"><div class="cardHead"><div><div class="caseTitle" id="caseTitle"></div><div id="caseId" style="font:10px ui-monospace;color:var(--muted)"></div></div><span id="caseStatus"></span></div><div class="summary" id="caseSummary"></div><div class="metaGrid"><div><span>Created</span><b id="caseCreated"></b></div><div><span>Last updated</span><b id="caseUpdated"></b></div></div></div><div class="card"><div class="cardHead"><h2>AI Triage Assertions</h2><button id="triage" class="primary">Run AI triage</button></div><div id="assertions"></div><div class="governance">AI output is advisory. Model suggestions are never treated as facts without linked evidence.</div></div><div class="card"><div class="cardHead"><h2>Missing Evidence Questions</h2></div><div id="questions"></div></div></div><aside><div class="card"><div class="cardHead"><h2>Evidence</h2><button id="addEvidence" class="secondary">Attach</button></div><div id="evidence"></div></div><div class="card"><div class="cardHead"><h2>Immutable Audit Ledger</h2></div><div id="audit"></div></div></aside></div></main></section></div>
<div id="caseModal" class="modal"><div class="modalBox"><div class="modalHead"><h2>Create a case</h2><button class="close" data-close="caseModal">×</button></div><form id="caseForm"><div class="field"><label>Title</label><input id="caseTitleInput" maxlength="200" placeholder="e.g. Primary health centre lacks essential medicines"></div><div class="field"><label>Problem summary</label><textarea id="caseSummaryInput" maxlength="10000" required placeholder="Describe the reported problem. Keep source claims as reported; verification comes later."></textarea></div><div class="modalActions"><button type="button" class="secondary" data-close="caseModal">Cancel</button><button class="primary">Create case</button></div></form></div></div>
<div id="evidenceModal" class="modal"><div class="modalBox"><div class="modalHead"><h2>Attach evidence</h2><button class="close" data-close="evidenceModal">×</button></div><form id="evidenceForm"><div class="field"><label>Assertion (optional)</label><select id="assertionSelect"><option value="">Case-level evidence</option></select></div><div class="field"><label>Source type</label><select id="sourceType"><option value="user_text">User text</option><option value="url">URL</option><option value="document_ref">Document reference</option></select></div><div class="field"><label>Evidence body</label><textarea id="evidenceBody" maxlength="50000" required placeholder="Paste the evidence or source excerpt."></textarea></div><div class="field"><label>Source URI (required for URL/document reference)</label><input id="sourceUri" maxlength="4000" placeholder="https://… or document reference"></div><div class="field"><label>Note</label><input id="evidenceNote" maxlength="4000" placeholder="Optional provenance note"></div><div class="modalActions"><button type="button" class="secondary" data-close="evidenceModal">Cancel</button><button class="primary">Attach evidence</button></div></form></div></div>
<script type="module">
import {{ createClient }} from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL={supabase_url!r}, SUPABASE_KEY={publishable_key!r};
const supabase=(SUPABASE_URL&&SUPABASE_KEY)?createClient(SUPABASE_URL,SUPABASE_KEY,{{auth:{{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}}}):null;
const $=id=>document.getElementById(id); let cases=[], current=null, signUp=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[m]));
const fmt=s=>s?new Date(s).toLocaleString([],{{dateStyle:'medium',timeStyle:'short'}}):'—';
function notice(text,error=false){{const n=$('globalNotice');n.textContent=text;n.className='notice'+(error?' error':'');n.hidden=!text; if(text)setTimeout(()=>n.hidden=true,5000)}}
function authNotice(text){{const n=$('authNotice');n.textContent=text;n.hidden=!text}}
function badge(v){{return `<span class="badge ${{esc(v)}}">${{esc(v).replace('_',' ')}}</span>`}}
function showApp(session){{$('authView').hidden=true;$('appView').hidden=false;$('userEmail').textContent=session.user.email||'';loadCases()}}
function showAuth(){{$('authView').hidden=false;$('appView').hidden=true}}
async function token(){{if(!supabase)throw Error('Supabase browser configuration is missing.');const r=await supabase.auth.getSession();if(r.error||!r.data.session){{showAuth();throw Error('Your session has expired. Please sign in again.')}}return r.data.session.access_token}}
async function api(path,options={{}}){{const t=await token();const r=await fetch(path,{{...options,headers:{{'Content-Type':'application/json','Authorization':'Bearer '+t,...(options.headers||{{}})}}}});let b={{}};try{{b=await r.json()}}catch{{}}if(!r.ok)throw Object.assign(Error(b.detail||`Request failed (${{r.status}})`),{{status:r.status}});return b}}
async function loadCases(){{try{{const b=await api('/api/v1/cases');cases=b.cases||[];renderCases()}}catch(e){{notice(e.message,true)}}}}
function renderCases(){{const q=$('search').value.toLowerCase(),st=$('status').value;const rows=cases.filter(c=>(!st||c.status===st)&&(!q||`${{c.title}} ${{c.summary}}`.toLowerCase().includes(q)));$('mTotal').textContent=cases.length;$('mOpen').textContent=cases.filter(c=>c.status==='open').length;$('mProgress').textContent=cases.filter(c=>c.status==='in_progress').length;$('mDone').textContent=cases.filter(c=>['resolved','closed'].includes(c.status)).length;$('caseRows').innerHTML=rows.length?rows.map(c=>`<tr data-id="${{esc(c.id)}}"><td data-label="Case"><b>${{esc(c.title)}}</b><small>${{esc(c.summary.slice(0,140))}}${{c.summary.length>140?'…':''}}</small></td><td data-label="Status">${{badge(c.status)}}</td><td data-label="Created">${{fmt(c.created_at)}}</td><td data-label="Updated">${{fmt(c.updated_at)}}</td></tr>`).join(''):`<tr><td colspan="4" style="text-align:center;padding:35px;color:var(--muted)">No cases match this view.</td></tr>`;document.querySelectorAll('#caseRows tr[data-id]').forEach(r=>r.onclick=()=>openCase(r.dataset.id))}}
async function openCase(id){{try{{current=await api('/api/v1/cases/'+encodeURIComponent(id));$('listView').style.display='none';$('detailView').style.display='grid';renderDetail()}}catch(e){{notice(e.message,true)}}}}
function renderDetail(){{const c=current.case;$('caseTitle').textContent=c.title;$('caseId').textContent=c.id;$('caseStatus').innerHTML=badge(c.status);$('caseSummary').textContent=c.summary;$('caseCreated').textContent=fmt(c.created_at);$('caseUpdated').textContent=fmt(c.updated_at);$('assertions').innerHTML=current.assertions.length?current.assertions.map(a=>`<div class="assertion"><div class="assertionTop"><div>${{badge(a.kind)}} <span style="font-size:11px;color:var(--muted)">${{a.created_by==='model'?'AI suggestion':'Reported'}}</span></div>${{a.evidence_ids.length?'<span class="badge fact">Evidence linked</span>':''}}</div><p>${{esc(a.text)}}</p><small>${{a.requires_evidence?'Evidence required for verification.':'No evidence requirement.'}}</small></div>`).join(''):'<p style="color:var(--muted)">No assertions yet.</p>';$('questions').innerHTML=current.missing_evidence_questions.length?current.missing_evidence_questions.map(q=>`<div class="question">${{esc(q)}}</div>`).join(''):'<p style="color:var(--muted)">Run triage to generate targeted evidence questions.</p>';$('evidence').innerHTML=current.evidence.length?current.evidence.map(e=>`<div class="evidence"><b>${{esc(e.source_type)}}</b><p>${{esc(e.body)}}</p>${{e.source_uri?`<div class="source">${{esc(e.source_uri)}}</div>`:''}}${{e.assertion_id?`<div class="source">Linked assertion: ${{esc(e.assertion_id)}}</div>`:''}}</div>`).join(''):'<p style="color:var(--muted)">No evidence attached.</p>';$('audit').innerHTML=current.audit_events.length?current.audit_events.map(a=>`<div class="audit"><b>${{esc(a.action)}}</b><small>${{fmt(a.created_at)}} · actor ${{esc(a.actor_subject)}}</small><div class="digest">SHA-256 ${{esc(a.payload_digest)}}</div></div>`).join(''):'<p style="color:var(--muted)">No audit events.</p>';populateAssertions()}}
function populateAssertions(){{$('assertionSelect').innerHTML='<option value="">Case-level evidence</option>'+current.assertions.map(a=>`<option value="${{esc(a.id)}}">${{esc(a.text.slice(0,100))}}</option>`).join('')}}
$('newCase').onclick=()=>openModal('caseModal');$('addEvidence').onclick=()=>openModal('evidenceModal');$('refresh').onclick=loadCases;$('search').oninput=renderCases;$('status').onchange=renderCases;$('back').onclick=()=>{{$('detailView').style.display='none';$('listView').style.display='block';current=null;loadCases()}};
$('triage').onclick=async()=>{{const b=$('triage');b.disabled=true;b.textContent='Triaging…';try{{current=await api('/api/v1/cases/'+encodeURIComponent(current.case.id)+'/triage',{{method:'POST',body:'{{}}'}});renderDetail();notice('AI triage completed. Review suggestions and evidence questions before verification.')}}catch(e){{notice(e.message,true)}}finally{{b.disabled=false;b.textContent='Run AI triage'}}}};
$('caseForm').onsubmit=async e=>{{e.preventDefault();try{{const b=await api('/api/v1/cases',{{method:'POST',body:JSON.stringify({{title:$('caseTitleInput').value.trim()||null,summary:$('caseSummaryInput').value}})}});closeModal('caseModal');$('caseForm').reset();await openCase(b.case.id);notice('Case created')}}catch(e){{notice(e.message,true)}}}};
$('evidenceForm').onsubmit=async e=>{{e.preventDefault();try{{await api('/api/v1/cases/'+encodeURIComponent(current.case.id)+'/evidence',{{method:'POST',body:JSON.stringify({{body:$('evidenceBody').value,source_type:$('sourceType').value,source_uri:$('sourceUri').value.trim()||null,note:$('evidenceNote').value.trim()||null,assertion_id:$('assertionSelect').value||null}})}});closeModal('evidenceModal');$('evidenceForm').reset();current=await api('/api/v1/cases/'+encodeURIComponent(current.case.id));renderDetail();notice('Evidence attached and audit event recorded')}}catch(e){{notice(e.message,true)}}}};
$('sourceType').onchange=()=>{{const t=$('sourceType').value;$('sourceUri').required=t!=='user_text'}};
function openModal(id){{$(''+id).style.display='flex'}}function closeModal(id){{$(''+id).style.display='none'}}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{{if(e.target===m)m.style.display='none'}});
$('switch').onclick=()=>{{signUp=!signUp;$('authSubmit').textContent=signUp?'Create account':'Sign in';$('switch').textContent=signUp?'Already have an account? Sign in':'Create an account';$('password').autocomplete=signUp?'new-password':'current-password';authNotice('')}};
$('authForm').onsubmit=async e=>{{e.preventDefault();if(!supabase)return authNotice('Supabase browser configuration is missing.');$('authSubmit').disabled=true;try{{const email=$('email').value.trim(),password=$('password').value;const r=signUp?await supabase.auth.signUp({{email,password}}):await supabase.auth.signInWithPassword({{email,password}});if(r.error)throw r.error;if(signUp&&!r.data.session)authNotice('Account created. Check your email to confirm, then sign in.');else if(r.data.session)showApp(r.data.session)}}catch(err){{authNotice(err.message||'Authentication failed.')}}finally{{$('authSubmit').disabled=false}}}};
$('logout').onclick=async()=>{{if(supabase)await supabase.auth.signOut();showAuth()}};
(async()=>{{if(!supabase)return authNotice('App configuration is missing. The owner must set Supabase browser credentials.');const r=await supabase.auth.getSession();if(r.data.session)showApp(r.data.session);supabase.auth.onAuthStateChange((_e,s)=>s?showApp(s):showAuth())}})();
</script></body></html>''')
